<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-07T15:42:27 IST" name="DemoSuite" finished-at="2022-07-07T15:43:26 IST" duration-ms="58605">
    <groups>
    </groups>
    <test started-at="2022-07-07T15:42:27 IST" name="DemoTest" finished-at="2022-07-07T15:43:26 IST" duration-ms="58605">
      <class name="com.sn.Testcases.ResolveInfoTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.sn.Testcases.ResolveInfoTest@141e5bef]" started-at="2022-07-07T15:42:34 IST" name="setup" finished-at="2022-07-07T15:43:01 IST" duration-ms="26997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ResolveIncident(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.sn.Testcases.ResolveInfoTest@141e5bef]" started-at="2022-07-07T15:43:01 IST" name="ResolveIncident" data-provider="ResolveIncidents" finished-at="2022-07-07T15:43:25 IST" duration-ms="23576" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Abraham Lincoln]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[DATABASE Email not working]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:819)
at org.testng.Assert.assertEquals(Assert.java:829)
at com.sn.Pages.ResolveInfo.ResolveIncident(ResolveInfo.java:197)
at com.sn.Testcases.ResolveInfoTest.ResolveIncident(ResolveInfoTest.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ResolveIncident -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.sn.Testcases.ResolveInfoTest@141e5bef]" started-at="2022-07-07T15:43:25 IST" name="teardown" finished-at="2022-07-07T15:43:26 IST" duration-ms="596" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.sn.Testcases.ResolveInfoTest -->
    </test> <!-- DemoTest -->
  </suite> <!-- DemoSuite -->
</testng-results>
